services:
  - type: worker
    name: mplugins-discord-bot
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: OWNER_ID
        sync: false
      - key: DATABASE_URL
        sync: false
